apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
  labels:
    app.kubernetes.io/part-of: node-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
        - name: node-server
          image: node-server:latest
          ports:
            - containerPort: 4000
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 4000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 4000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: node-server
  labels:
    app.kubernetes.io/part-of: node-server-app
spec:
  selector:
    app: node-server
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: node-server
  labels:
    app.kubernetes.io/part-of: node-server-app
spec:
  port:
    targetPort: 4000
  to:
    kind: Service
    name: node-server

