apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
  labels:
    app.kubernetes.io/part-of: node-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
        - name: node-server
          image: node-server:latest
          ports:
            - name: http-4000        # <-- Assigned string name to container port
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: http-4000        # <-- Referenced the named port
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: http-4000        # <-- Referenced the named port
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: node-server
  labels:
    app.kubernetes.io/part-of: node-server-app
spec:
  selector:
    app: node-server
  ports:
    - name: http-4000                # <-- Match string name here
      protocol: TCP
      port: 4000
      targetPort: http-4000          # <-- Targets named container port
  type: ClusterIP

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: node-server
  labels:
    app.kubernetes.io/part-of: node-server-app
spec:
  port:
    targetPort: http-4000            # <-- Targets named service port
  to:
    kind: Service
    name: node-server

